global:
  image:
    repository: ghcr.io/kl-engineering/subscriptions-microgateway
    pullPolicy: Always
    tag: 0.0.17

  region: "uk"
  environment: "apifactory"

  imagePullSecrets:
    - name: dockerconfigjson-ghcr
  nameOverride: "subscriptions-microgateway"
  fullnameOverride: "subscriptions-microgateway"
