kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  labels:
    app: subscriptions
  name: dockerconfigjson-ghcr
  namespace: subscriptions
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJhMnd0Wlc1bmFXNWxaWEpwYm1jNloyaHdYMDkwY0c1QmEzbGFORXhCYUUxV2FUYzFPR2hGYTNOaFVURjNjbXhvY1RKTFNEZElhQT09In19fQ==
