{{- $fullName := include "workspace.fullname" . -}}
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
spec:
  organization: {{ .Values.tf_organization }}
  secretsMountPath: "/tmp/secrets"
  sshKeyID: "TFC GitHub"
  module:
    source: "git@github.com:KL-Engineering/subscriptions-terraform-module.git?ref=v0.1.1"
  outputs:
    - key: my_bucket_region
      moduleOutputName: bucket_region
  variables:
    - key: region
      value: "eu-west-2"
      sensitive: false
      environmentVariable: false
    - key: aws_target_role_arn
      sensitive: true
      environmentVariable: false
    - key: aws_session_name
      sensitive: true
      environmentVariable: false
    - key: aws_target_external_id
      sensitive: true
      environmentVariable: false
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true