{{- $fullName := include "workspace.fullname" . -}}
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
spec:
  organization: {{ .Values.tf_organization }}
  secretsMountPath: "/tmp/secrets"
  sshKeyID:
    valueFrom:
      configMapKeyRef:
        name: tfe-module-deps
        key: tfe_ssh_key_id
  module:
    source: "git@github.com:KL-Engineering/subscriptions-terraform-module.git?ref=v0.1.0"
  outputs:
    - key: my_bucket_region
      moduleOutputName: bucket_region
  variables:
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true