# Default values for workspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kl-base-terraform:
  fullnameOverride: workspace-apifactory-uk
  module:
    source: git@github.com:KL-Engineering/subscriptions-terraform-module.git
    version: v1.0.4
  provider_config:
    aws_region: eu-west-2
  outputs:
    - key: db_endpoint
      moduleOutputName: db_endpoint
    - key: db_name
      moduleOutputName: db_name
    - key: db_master_username
      moduleOutputName: db_master_username
    - key: db_password
      moduleOutputName: db_password
    - key: db_port
      moduleOutputName: db_port
  variables:
    - key: project_environment
      value: apifactory
      sensitive: false
      environmentVariable: false
    - key: project_region
      value: uk
      sensitive: false
      environmentVariable: false
    - key: service_owner
      value: infrastructure
      sensitive: false
      environmentVariable: false
    - key: project
      value: subscriptions
      sensitive: false
      environmentVariable: false
    - key: db_name
      value: subscriptions_db
      sensitive: false
      environmentVariable: false
    - key: db_service
      value: subscriptions
      sensitive: false
      environmentVariable: false
    - key: enhanced_monitoring_role_enabled
      value: "false"
      sensitive: false
      environmentVariable: false
    - key: deletion_protection
      value: "false"
      sensitive: false
      environmentVariable: false
