# Default values for workspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "workspace-apifactory-uk"
tf_organization: "kidsloop-infrastructure"