name: Propagate release candidate

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      base_ref:
        required: true
        type: string
      target_ref:
        required: true
        type: string
      base_env:
        required: true
        type: string
      target_env:
        required: true
        type: string

jobs:
  propagate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate changeset
        id: generate-diff
        run: |
          git format-patch ${{ inputs.base_ref }} ${{ inputs.target_ref }} -o /tmp/patches ${{ inputs.base_env }}

          FILES="/tmp/patches/*.patch"
          for f in $FILES 
          do
            git apply -p4 --directory="${{ inputs.target_env }}" $f
          done

          git config --global user.name 'gitops-propagate-sync'
          git config --global user.email 'github-action@noreply.github.com'

          BRANCH_NAME=propagate/${{ github.run_id }}-${{ github.run_attempt }}

          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "chore(propagate-sync): propagate version ${{ inputs.target_ref }} in ${{ inputs.base_env }} into ${{ inputs.target_env }}" && git push --set-upstream origin $BRANCH_NAME || touch no-commit

          if [ -f "no-commit" ]; then
            echo "::set-output name=commit-status::no-commit"
          else 
            echo "::set-output name=pr-branch-name::$BRANCH_NAME"
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        if: steps.generate-diff.outputs.commit-status != 'no-commit'
        with:
          branch: ${{ steps.generate-diff.outputs.pr-branch-name }}
          delete-branch: true
          title: "Propagate release candidate from ${{ inputs.base_env }} into ${{ inputs.target_env }}"
          body: |
            The changes in the files between version ${{ inputs.base_ref }} and ${{ inputs.target_ref }} in environment ${{ inputs.base_env }}
            has been applied to the ${{ inputs.target_env }}
          labels: |
            automated pr
            release candidate
